Repository jeroennoten/Laravel-AdminLTE, pull requests merged in 2019-07, with the labels that each got.

#307 update adminlte from v2.4.0 to v2.4.12
  resources/assets/dist/css/AdminLTE.css
  resources/assets/dist/css/AdminLTE.min.css
  resources/assets/dist/css/skins/skin-black-light.css
  resources/assets/dist/css/skins/skin-black-light.min.css
  resources/assets/dist/css/skins/skin-black.css
  resources/assets/dist/css/skins/skin-black.min.css
  resources/assets/dist/css/skins/skin-blue-light.css
  resources/assets/dist/css/skins/skin-blue-light.min.css
  resources/assets/dist/css/skins/skin-blue.css
  resources/assets/dist/css/skins/skin-blue.min.css
  resources/assets/dist/css/skins/skin-green-light.css
  resources/assets/dist/css/skins/skin-green-light.min.css
  resources/assets/dist/css/skins/skin-green.css
  resources/assets/dist/css/skins/skin-green.min.css
  resources/assets/dist/css/skins/skin-purple-light.css
  resources/assets/dist/css/skins/skin-purple-light.min.css
  resources/assets/dist/css/skins/skin-purple.css
  resources/assets/dist/css/skins/skin-purple.min.css
  resources/assets/dist/css/skins/skin-red-light.css
  resources/assets/dist/css/skins/skin-red-light.min.css
  resources/assets/dist/css/skins/skin-red.css
  resources/assets/dist/css/skins/skin-red.min.css
  resources/assets/dist/css/skins/skin-yellow-light.css
  resources/assets/dist/css/skins/skin-yellow-light.min.css
  resources/assets/dist/css/skins/skin-yellow.css
  resources/assets/dist/css/skins/skin-yellow.min.css
Labels: enhancement

#116 menu translation using filter class
  config/adminlte.php
  src/Menu/Filters/LangFilter.php
  tests/Menu/BuilderTest.php
  tests/TestCase.php
Labels: enhancement, next, question

#63 Translate menu items using lang files
  README.md
  config/adminlte.php
  resources/lang/en/menu.php
  resources/lang/pt-br/menu.php
  resources/views/partials/menu-item-top-nav.blade.php
  resources/views/partials/menu-item.blade.php
Labels: enhancement, next

#255 Fixed sidebar submenu active check
  resources/assets/dist/css/skins/skin-blue.css
  src/Menu/ActiveChecker.php
  src/Menu/Filters/ClassesFilter.php
  src/Menu/Filters/SubmenuFilter.php
  tests/TestCase.php
Labels: bug

#161 Add footer at page.blade.php
  resources/views/page.blade.php
Labels: enhancement

#301 Added regex evaluation for active menu items.
  README.md
  src/Menu/ActiveChecker.php
  tests/Menu/ActiveCheckerTest.php
Labels: enhancement, invalid

#131 Fix active highlighting on route set menu items, fix multiple active submenu items.
  src/Menu/ActiveChecker.php
  src/Menu/Filters/HrefFilter.php
  tests/Menu/ActiveCheckerTest.php
Labels: bug, next
